[project]
name = "beecrowd-python"
version = "0.1.0"
description = "RepositÃ³rio com minhas soluÃ§Ãµes dos problemas do Beecrowd (antigo URI Online Judge) em Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []